name: .NET Core Desktop

on:
  push:
    branches: [ "private_test" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      Solution_Name: SomeRandomBenchmark

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Build the application
      run: dotnet build --configuration Release -o ./bin/

    - name: Run benchmark
      run: ./bin/SomeRandomBenchmark
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.1
      with:
        name: result ${{ github.sha }}
        path: ./BenchmarkDotNet.Artifacts

